services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=backend.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
